USE [master]
GO

/****** Object:  Database [messageboard]    Script Date: 1/24/2019 2:01:48 AM ******/
CREATE DATABASE [messageboard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'messageboard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\messageboard.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'messageboard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\messageboard_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [messageboard] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [messageboard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [messageboard] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [messageboard] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [messageboard] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [messageboard] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [messageboard] SET ARITHABORT OFF 
GO

ALTER DATABASE [messageboard] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [messageboard] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [messageboard] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [messageboard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [messageboard] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [messageboard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [messageboard] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [messageboard] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [messageboard] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [messageboard] SET  DISABLE_BROKER 
GO

ALTER DATABASE [messageboard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [messageboard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [messageboard] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [messageboard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [messageboard] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [messageboard] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [messageboard] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [messageboard] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [messageboard] SET  MULTI_USER 
GO

ALTER DATABASE [messageboard] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [messageboard] SET DB_CHAINING OFF 
GO

ALTER DATABASE [messageboard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [messageboard] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [messageboard] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [messageboard] SET  READ_WRITE 
GO

